### ISSUE TITLE
Button seems broken in 0.2.3

### ISSUE THREAD

**Issue by escobera** [surface-ui/surface_bootstrap#11]
Hi there @olivermt, I'm getting 
```
02:21:27.286 [error] #PID<0.1031.0> running Surface.Catalogue.Server.Endpoint (connection #PID<0.944.0>, stream id 4) terminated
Server: localhost:4001 (http)
Request: GET /examples/SurfaceBootstrap.Catalogue.Button.Example04?__window_id__=CE86ED905FF107321E45360D07B287C0
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Keyword.get/3
        (elixir 1.11.3) lib/keyword.ex:218: Keyword.get(%{__changed__: %{__context__: true, __surface__: true, aria_disabled: true, aria_hidden: true, aria_label: true, breakpoint: true, class: true, default: true, flash: true, id: true, inner_block: true}, __context__: %{}, __surface__: %{provided_templates: [:default], slots: %{default: %{size: 1}}}, aria_disabled: nil, aria_hidden: nil, aria_label: nil, breakpoint: nil, class: [], default: [%{}], flash: %{}, id: nil, inner_block: #Function<1.36278796/2 in SurfaceBootstrap.Catalogue.Button.Example04.render/1>, socket: #Phoenix.LiveView.Socket<assigns: #Phoenix.LiveView.Socket.AssignsNotInSocket<>, changed: %{__context__: true, __surface__: true, aria_disabled: true, aria_hidden: true, aria_label: true, breakpoint: true, class: true, ...}, endpoint: Surface.Catalogue.Server.Endpoint, id: "example", parent_pid: #PID<0.1031.0>, root_pid: nil, router: Surface.Catalogue.Server.Router, transport_pid: nil, view: SurfaceBootstrap.Catalogue.Button.Example04, ...>}, :disabled, nil)
        (surface_bootstrap 0.2.3) lib/surface_bootstrap/container.ex:8: anonymous fn/3 in SurfaceBootstrap.Container.set_aria_base_attrs/1
        (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
        (surface_bootstrap 0.2.3) lib/surface_bootstrap/container.ex:24: anonymous fn/2 in SurfaceBootstrap.Container.render/1
        (phoenix_live_view 0.15.7) lib/phoenix_live_view/diff.ex:356: Phoenix.LiveView.Diff.traverse/6
        (phoenix_live_view 0.15.7) lib/phoenix_live_view/diff.ex:430: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
        (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.15.7) lib/phoenix_live_view/diff.ex:356: Phoenix.LiveView.Diff.traverse/6

```

when trying to access the button examples in the catalogue as well as in my app. It seems to have been introduced in https://github.com/surface-ui/surface_bootstrap/commit/44360f73b9d45cd95de784588372045473a16e5c and is probably related to trying to access `assigns`which is a map using `Keyword.get`, but I don't think I can propose a fix here since I'm still new to this codebase.

**Comment by olivermt** [comment]
Thanks, will investigate shortly!

Regards,
Oliver Mulelid-Tynes
Chairman
OMT Tech AS
+47 92 08 92 98
________________________________
From: Rafael Barbosa ***@***.***>
Sent: Wednesday, June 23, 2021 7:32:34 AM
To: surface-ui/surface_bootstrap ***@***.***>
Cc: Oliver Mulelid-Tynes ***@***.***>; Mention ***@***.***>
Subject: [surface-ui/surface_bootstrap] Button seems broken in 0.2.3 (#11)


Hi there @olivermt<https://github.com/olivermt>, I'm getting

02:21:27.286 [error] #PID<0.1031.0> running Surface.Catalogue.Server.Endpoint (connection #PID<0.944.0>, stream id 4) terminated
Server: localhost:4001 (http)
Request: GET /examples/SurfaceBootstrap.Catalogue.Button.Example04?__window_id__=CE86ED905FF107321E45360D07B287C0
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Keyword.get/3
        (elixir 1.11.3) lib/keyword.ex:218: Keyword.get(%{__changed__: %{__context__: true, __surface__: true, aria_disabled: true, aria_hidden: true, aria_label: true, breakpoint: true, class: true, default: true, flash: true, id: true, inner_block: true}, __context__: %{}, __surface__: %{provided_templates: [:default], slots: %{default: %{size: 1}}}, aria_disabled: nil, aria_hidden: nil, aria_label: nil, breakpoint: nil, class: [], default: [%{}], flash: %{}, id: nil, inner_block: #Function<1.36278796/2 in SurfaceBootstrap.Catalogue.Button.Example04.render/1>, socket: #Phoenix.LiveView.Socket<assigns: #Phoenix.LiveView.Socket.AssignsNotInSocket<>, changed: %{__context__: true, __surface__: true, aria_disabled: true, aria_hidden: true, aria_label: true, breakpoint: true, class: true, ...}, endpoint: Surface.Catalogue.Server.Endpoint, id: "example", parent_pid: #PID<0.1031.0>, root_pid: nil, router: Surface.Catalogue.Server.Router, transport_pid: nil, view: SurfaceBootstrap.Catalogue.Button.Example04, ...>}, :disabled, nil)
        (surface_bootstrap 0.2.3) lib/surface_bootstrap/container.ex:8: anonymous fn/3 in SurfaceBootstrap.Container.set_aria_base_attrs/1
        (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
        (surface_bootstrap 0.2.3) lib/surface_bootstrap/container.ex:24: anonymous fn/2 in SurfaceBootstrap.Container.render/1
        (phoenix_live_view 0.15.7) lib/phoenix_live_view/diff.ex:356: Phoenix.LiveView.Diff.traverse/6
        (phoenix_live_view 0.15.7) lib/phoenix_live_view/diff.ex:430: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
        (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.15.7) lib/phoenix_live_view/diff.ex:356: Phoenix.LiveView.Diff.traverse/6



when trying to access the button examples in the catalogue as well as in my app. It seems to have been introduced in 44360f7<https://github.com/surface-ui/surface_bootstrap/commit/44360f73b9d45cd95de784588372045473a16e5c> and is probably related to trying to access assignswhich is a map using Keyword.get, but I don't think I can propose a fix here since I'm still new to this codebase.

**Comment by olivermt** [comment]
You can find 0.2.4 on hex with this fixed now
