### ISSUE TITLE
Bump Ecto version?

### ISSUE THREAD

**Issue by jasonmj** [surface-ui/surface_bootstrap#6]
I just started a new project with mix phx.new and tried to add surface_bootstrap. When I run mix deps.get, it fails because ecto version 3.5.5 is required by surface_bootstrap, but ecto version 3.6.1 was installed by the phx.new generator. Is there anything holding surface_bootstrap back from this version bump?

Also, I should note that this isn't really an "issue" that blocks use of the library. If you start fresh by removing the deps directory and mix.lock, mix deps.get succeeds with no issue. 

Mostly, I'm just curious if there are any compatibility issues or blockers. No rush here. Feel free to close without a proper answer too. I maybe should have asked on Slack instead.

**Comment by olivermt** [comment]
Hey! This is a good arena to ask.

I will make it depend on "=> 3.0.0" which should solve this.

**Comment by olivermt** [comment]
after some talk on slack we arrived at ~> 3.5 which will give anything 3.5 and up to 4.0
